services:
  nginx:
    image: nginx:latest
    hostname: nginx
    volumes:
      - "/home/ttutko/repos/keycloaktesting/nginx.conf:/etc/nginx/nginx.conf"
      - "/home/ttutko/repos/keycloaktesting/openssl/server.crt:/etc/ssl/server.crt"
      - "/home/ttutko/repos/keycloaktesting/openssl/server.key:/etc/ssl/server.key"
    networks:
      backend:
    ports:
      - "8096:8096"
    depends_on:
      - keycloak

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    networks:
      - backend
    environment:
      - KC_DB_PASSWORD=postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB=postgres
      - KC_HOSTNAME_URL=https://localhost:8096/auth
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_PROXY_HEADERS=xforwarded
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start --optimized --hostname-debug=true
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1
    networks:
      - backend
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak

networks:
  backend:
    attachable: true
    driver: overlay
